### ISSUE TITLE
凯亚名字

### ISSUE THREAD

**Issue by 29681** [SpeedyOrc-C/Irminsul#19]
凯亚.莱艮芬德 应该为 凯亚.亚尔伯里奇

**Comment by SpeedyOrc-C** [comment]
不需要担心，另一个名字早已写好，只是还没展示出来。

[请看这里](https://github.com/SpeedyOrc-C/Irminsul/blob/d4efab03d746e8c11eebb1ddef1374a4631a9c91/irminsul-api/app/Root/Teyvat/Khaenriah.hs#L13)
