### ISSUE TITLE
提高触摸屏使用体验的建议

### ISSUE THREAD

**Issue by otomad** [SpeedyOrc-C/Irminsul#20]
请问可以为网页样式添加以下声明来提高触摸屏的使用体验吗？

```css
touch-action: none;
```

由于使用手机浏览时，页面的内容过大，因此只能够通过开启电脑版访问来使其显示得更小。此时由于进入子区域需要进行**双击**操作，然而这将会触发浏览器的双击放大操作。此时需要通过添加上述样式来屏蔽浏览器的默认放大操作，转而执行自己的双击操作。

**Comment by SpeedyOrc-C** [comment]
感谢建议，我的一些朋友用过之后也说了双击会不小心放大，但我几乎没有在手机上测试过。

请问这个是直接加到 `body` 上就可以了吗？

**Comment by otomad** [comment]
也许可以修改成

```css
touch-action: manipulation;
```

这将会只屏蔽双击放大的操作，而滑动页面、双指放大手势会保留。

不过当页面意外放大之后，手指拖动右下角的摇杆可能会和页面滑动手势冲突。

另一种就是

```css
touch-action: pinch-zoom;
```

这将只保留双指放大缩小的手势，滑动页面、双击放大都会屏蔽。也许可以将意外放大的页面缩小回来。

**Comment by SpeedyOrc-C** [comment]
好的，那就只禁用双击吧。摇杆的移动是加了 `preventDefault` 的。
